// Transcribed from the saved article PDFs, not fetched from Medium at runtime.
// Body wording and order are preserved. Platform UI, profile bios, print headers,
// and footers are excluded. The one authored CTA omission is disclosed below.
export const fightLegendsSamples = [
  {
    slug: "introducing-nix",
    title: "Introducing “Nix” from Fight Legends",
    format: "Character lore",
    published: "December 30, 2021",
    sourceFile: "Introducing “Nix” from Fight Legends _ by Fight Legends _ Medium.pdf",
    image: "/assets/fight-legends/nix-article-artwork.png",
    alt: "Original Fight Legends article artwork showing Nix’s character concept from three angles and her cybernetic limbs",
    archiveNote: "Article text and original artwork preserved from the saved publication. Medium interface elements and browser print headers and footers omitted.",
    blocks: [
      { text: "Sil Nix, also known simply by her street name Nix, is a soon-to-be playable character in the #NFT powered Fight Legends video game and the first female character on the roster!" },
      { text: "A scrappy, street rat-style zoner, Nix’s quick and agile attacks are supplemented by augmented limbs forced upon her during experimentation by the Agency, an organization steeped in secrecy." },
      { text: "Born after the first rift-wars on the streets of the biggest futuristic city remaining on Earth, Nix was abducted at an early age and sent into the Agency’s secret program where they experimented on humans towards the furtherment of cybernetic technology." },
      { text: "Nix undertook severe experimentation, leaving her with cybernetic limbs on the right side of her body that allow her to extend her limbs several feet further out than before. Boosted through energy exertion, the limb extensions are quickly deployed and perfect for playing footsies on the outside of her opponents’ attack range!" },
      { text: "Through toughness and cunning Nix managed to escape the Agency’s facility and has since survived on the streets of the city honing her fight skills towards hunting down and gaining revenge on those who abducted her." },
      { text: "Now living life with a chip on her shoulder and an inherent hatred for the Agency and its anonymous members, she is hoping that competing in the Fight Legend battles will lead her to find the people responsible for her abduction and forced experimentation." },
      { heading: "APPEARANCE" },
      { text: "Nix has a style that lends to her futuristic street existence. Nix has brightly dyed hair in a crazy punk style and scruffy but bright, punk-inspired clothing. This includes a casually worn sporty jacket worn open over a bikini top and short, tight leather shorts over fishnets." },
      { text: "Nix’s right arm and leg are now mechanic add-ons capable of extension and other possible special moves. The limbs have been tagged up with anarchistic symbols and anti-social rhetoric." },
    ],
  },
  {
    slug: "nix-vs-ross-levine",
    title: "Nix vs Ross Levine | Fight Legends",
    format: "Matchup storytelling",
    published: "March 2, 2022",
    sourceFile: "Nix vs Ross Levine _ Fight Legends _ by Fight Legends _ Medium.pdf",
    image: "/assets/fight-legends/nix-ross-article-artwork.png",
    alt: "Original Fight Legends fantasy tournament artwork pairing Nix with Ross Levine",
    archiveNote: "Article text and original artwork preserved from the saved publication. Medium interface elements and browser print headers and footers omitted.",
    blocks: [
      { text: "It’s fight week of the Fight Legends fantasy fight tournament semi-finals! The first match of this tournament round is an epic showdown as in-game character and IRL athlete Ross TURBO Levine meets up against Nix." },
      { text: "This will prove to be an epic fight that will go down in Fight Legends history!" },
      { text: "For Nix, she’ll need to use her extendable limbs to establish her zoner style and keep away from Levine, who will have a considerable reach disadvantage." },
      { text: "TURBO on the other hand, with his calf and head kicks, will have to try and beat Nix to the strike and show off his KO kicking power. Perhaps Ross will try to utilize his calf kicks at midrange before closing the distance and landing with hooks and kicks to the head?" },
      { text: "We can’t wait to see what paths to victory these fighters look to impress on one another in this fight for the ages!" },
    ],
  },
  {
    slug: "story-mode",
    title: "Story Mode | Fight Legends",
    format: "Player-facing game explanation",
    published: "January 19, 2022",
    sourceFile: "Story Mode _ Fight Legends. Sometimes you just love experiencing… _ by Fight Legends _ Medium.pdf",
    image: "/assets/fight-legends/story-mode-article-artwork.png",
    alt: "Original Fight Legends Story Mode article artwork",
    archiveNote: "Article text and original artwork preserved from the saved publication. Medium interface elements and browser print headers and footers omitted. The closing invitation to join Discord for early access has been omitted because it is no longer current.",
    blocks: [
      { heading: "Fight Legends PVE Mode" },
      { text: "Sometimes you just love experiencing good lore and character-building, other times one just grows tired of getting pwnd online. Either way, a great fighting game should always have a story mode that feels like more than just a second thought to the development team." },
      { text: "At Fight Legends, we’re taking Story Mode to the next level with amazing incentives to explore the world and travel the multiverse competing for hand-to-hand combat supremacy. Starting on an Earth far in the future, PVE Story Mode will allow players to learn the background and personality of their favorite Fighters while players win fights, clear maps and more." },
      { text: "The Fight Legends development team is determined to design Story Mode AI that facilitates player skill-building. AI won’t just get better in intangible ways. Instead, slight alterations in the AI’s own strategy and maneuvers will lead players themselves to learn increasingly complex strategies and maneuvers in order to successfully complete each level." },
      { text: "That way, new and old players alike can play and earn in story mode while building their skills with their favorite fighter until they’re ready for online action in our PVP Mode!" },
      { heading: "Story Mode Rewards" },
      { text: "Fight Legends PVE Mode can be played with any in-game NFT Fighter, with your progress being rewarded as you fight through game areas. While purchasing an NFT Fighter will always be an option towards earning, those who may not be ready to buy can Free Hire a Fighter from another player and split the rewards they earn!" },
      { text: "The first playable map in Fight Legends Story Mode will be a future Earth made up of sub-regions. Regions of the map will contain event markers that represent fights a player must choose between and win in order to progress. Once a certain number of these events have been completed, a regional mini-boss will challenge the player. Beating all of a map’s mini-bosses will unlock the final Boss battle for completion of the entire map." },
      { text: "Beyond the typical fight game character storylines, end-scenes, and in-game achievement trophies, Fight Legends Story Mode brings that energy way up with the extra incentive of earning crypto and being rewarded with owned in-game assets in the form of NFTs!" },
      { text: "This addition of blockchain technology incentivizes players to not just play through the mode once, but again with every character possible towards building the ultimate Fight Legends NFT collection!" },
    ],
  },
] as const;
