export const featuredContent = [
  {
    slug: "fight-legends-development-show",
    project: "Fight Legends",
    format: "Dev update episode",
    title: "Fight Legends Dev Update",
    summary: "A recurring development format made an unfinished fighting game visible, understandable, and worth returning to between milestones.",
    contribution: "Concept, format, visual direction, editing, hosting support, episode packaging, and social distribution.",
    shortCredit: "Format · edit · episode packaging",
    impact: "25% increase in YouTube subscribers and approximately 30% higher social engagement.",
    href: "/case-studies/fight-legends",
    orientation: "landscape",
    categories: ["Video", "Gaming", "Social"],
    media: { type: "video", src: "/assets/fight-legends/dev-update-22.mp4", poster: "/assets/fight-legends/dev-update-22-poster.png", alt: "Fight Legends development update episode 22 clip" },
  },
  {
    slug: "edge-interview-social-cut",
    project: "Edge of Company",
    format: "Vertical social interview",
    title: "Edge of NFT Social Interview",
    summary: "Short-form packaging gave an interview a second life beyond the episode and created a clear on-ramp for new viewers.",
    contribution: "Guest framing, interview production, vertical edit, captioning direction, and channel packaging.",
    shortCredit: "Interview production · vertical edit · captions",
    impact: "Part of a system that added 17,800 YouTube views and grew followers 35%.",
    href: "/case-studies/edge-of-company",
    orientation: "portrait",
    categories: ["Podcast", "Interview", "Social"],
    media: { type: "video", src: "/assets/edge-of-company/edge-storyco-short.mp4", alt: "StoryCo vertical short-form clip produced for Edge of Company" },
  },
  {
    slug: "edge-show-hot-topics",
    project: "Edge of Company",
    format: "Show production",
    title: "Edge of NFT Show — Hot Topics",
    summary: "A landscape episode example showing the recurring show format, overlay system, and interview packaging in context.",
    contribution: "Show production, overlay direction, interview packaging, and episode publishing.",
    shortCredit: "Show production · overlay design · episode packaging",
    impact: "A representative long-form show asset from the Edge of NFT production system.",
    href: "/case-studies/edge-of-company",
    orientation: "landscape",
    categories: ["Show", "Interview", "Production"],
    media: { type: "video", src: "/assets/edge-of-company/edge-hot-topics.mp4", alt: "Edge of NFT Hot Topics show clip" },
  },  {
    slug: "dadabots-interview",
    project: "Web3 Metal",
    format: "Interview & visual package",
    title: "DADABOTS Interview",
    summary: "An experimental subject shaped into a concise creator story without sanding off what made it strange and interesting.",
    contribution: "Interview direction, editorial framing, custom overlay design, edit, and distribution packaging.",
    shortCredit: "Interview direction · overlay design · edit",
    impact: "Connected emerging music technology to a creator audience through an accessible, personality-led format.",
    href: "/content/podcast-show-overlay-design",
    orientation: "landscape",
    categories: ["Interview", "Music", "Creator work"],
    media: { type: "video", src: "/assets/dadabots-interview-clip-web.mp4", alt: "DADABOTS interview clip produced for Web3 Metal" },
  },
  {
    slug: "edge-episode-packaging",
    project: "Edge of Company",
    format: "YouTube thumbnail design",
    title: "Edge of NFT YouTube thumbnail system",
    summary: "A visual system that makes a long-form episode legible at a glance while keeping the show identity recognizable across releases.",
    contribution: "Thumbnail composition, title treatment, guest hierarchy, and social-ready visual packaging.",
    shortCredit: "Thumbnail design · show identity · episode packaging",
    impact: "A repeatable visual language for interview episodes and their social cutdowns.",
    href: "/case-studies/edge-of-company",
    orientation: "landscape",
    categories: ["Design", "Packaging", "Interview"],
    media: { type: "image", src: "/assets/future-of-storytelling.jpeg", alt: "Edge of NFT Future of Storytelling episode packaging", width: 1280, height: 720 },
  },
  {
    slug: "edge-nft-toonstar",
    project: "Edge of Company",
    format: "Edge of NFT episode thumbnail",
    title: "Toonstar / The future of AI & Web3 entertainment",
    summary: "A high-contrast episode thumbnail system that combines show identity, guest recognition, and a clear editorial hook.",
    contribution: "Thumbnail composition, title treatment, guest hierarchy, and visual packaging.",
    shortCredit: "Thumbnail design · show identity · episode packaging",
    impact: "Made a long-form conversation legible as a distinct episode before the viewer presses play.",
    href: "/content/graphic-design",
    orientation: "landscape",
    categories: ["Design", "Packaging", "Edge of NFT"],
    media: { type: "image", src: "/assets/edge-of-company/edge-nft-toonstar.png", alt: "Edge of NFT Toonstar episode thumbnail", width: 1280, height: 720 },
  },
  {
    slug: "edge-nft-veecon",
    project: "Edge of Company",
    format: "Edge of NFT episode thumbnail",
    title: "VeeCon / Edge of NFT",
    summary: "A vivid event-led thumbnail treatment built around recognizable guests, a strong location cue, and a repeatable show frame.",
    contribution: "Thumbnail composition, color direction, guest labeling, and episode packaging.",
    shortCredit: "Thumbnail design · event packaging · visual system",
    impact: "Gave an event-focused interview a consistent visual entry point across the channel.",
    href: "/content/graphic-design",
    orientation: "landscape",
    categories: ["Design", "Packaging", "Edge of NFT"],
    media: { type: "image", src: "/assets/edge-of-company/edge-nft-veecon.png", alt: "Edge of NFT VeeCon episode thumbnail", width: 1280, height: 720 },
  },
  {
    slug: "edge-nft-art-basel-benzi",
    project: "Edge of Company",
    format: "Edge of NFT episode thumbnail",
    title: "Art Basel / Benzi",
    summary: "A location-forward thumbnail that turns a field interview into a recognizable, scroll-stopping episode package.",
    contribution: "Thumbnail layout, typographic hierarchy, color system, and social-ready packaging.",
    shortCredit: "Thumbnail design · typography · episode packaging",
    impact: "Connected the guest, place, and show identity in one compact visual frame.",
    href: "/content/graphic-design",
    orientation: "landscape",
    categories: ["Design", "Packaging", "Edge of NFT"],
    media: { type: "image", src: "/assets/edge-of-company/edge-nft-art-basel-benzi.png", alt: "Edge of NFT Art Basel Benzi episode thumbnail", width: 1280, height: 720 },
  },
  {
    slug: "edge-nft-art-basel-adam",
    project: "Edge of Company",
    format: "Edge of NFT episode thumbnail",
    title: "Art Basel / Adam Charles",
    summary: "A second Art Basel treatment showing how the same show language can flex around a different guest and story.",
    contribution: "Thumbnail layout, guest emphasis, title treatment, and visual packaging.",
    shortCredit: "Thumbnail design · guest framing · show identity",
    impact: "Extended a recognizable episode system across multiple field interviews.",
    href: "/content/graphic-design",
    orientation: "landscape",
    categories: ["Design", "Packaging", "Edge of NFT"],
    media: { type: "image", src: "/assets/edge-of-company/edge-nft-art-basel-adam.png", alt: "Edge of NFT Art Basel Adam Charles episode thumbnail", width: 1280, height: 720 },
  },
  {
    slug: "web3-metal-editorial-package",
    project: "Web3 Metal",
    format: "Editorial & campaign work",
    title: "Editorial systems for creator work",
    summary: "Newsletter and campaign assets that gave an experimental music project a consistent voice, cadence, and visual world.",
    contribution: "Editorial framing, campaign copy, visual direction, publishing rhythm, and audience packaging.",
    shortCredit: "Editorial direction · campaign copy · visual system",
    impact: "A repeatable publishing system for creator-led stories, releases, and community programming.",
    href: "/content/writing",
    orientation: "landscape",
    categories: ["Editorial", "Campaigns", "Creator work"],
    media: { type: "image", src: "/assets/writing-healthcare-podcast.jpg", alt: "International Examiner healthcare podcast article", width: 1280, height: 720 },
  },
{
    slug: "dadabots-short-01",
    project: "Web3 Metal",
    format: "Short-form visual",
    title: "DADABOTS — Prodigy vs NIN",
    summary: "A vertical social asset that turns an artist interview into a focused, mobile-first visual moment.",
    contribution: "Interview packaging, visual direction, vertical framing, and YouTube Shorts publishing.",
    shortCredit: "Vertical edit · overlay design · publishing",
    impact: "Built to give a niche creator story a clear entry point in the social feed.",
    href: "/case-studies/cyber-metal-radio",
    orientation: "portrait",
    categories: ["Short Form", "Overlay", "Music"],
    media: { type: "video", src: "/assets/web3-metal/dadabots-prodigy-vs-nin.mp4", poster: "/assets/web3-metal/dadabots-short-01-clean.png", alt: "DADABOTS Prodigy vs NIN vertical short-form video" },
  },
  {
    slug: "dadabots-short-02",
    project: "Web3 Metal",
    format: "Short-form visual",
    title: "DADABOTS — Atari Teenage Riot vs Aphex Twin",
    summary: "A second vertical treatment showing how the same interview system can produce distinct social-ready moments.",
    contribution: "Overlay design, vertical composition, short-form edit direction, and YouTube Shorts publishing.",
    shortCredit: "Vertical edit · overlay design · publishing",
    impact: "A companion cut that extends the interview’s life beyond the original conversation.",
    href: "/case-studies/cyber-metal-radio",
    orientation: "portrait",
    categories: ["Short Form", "Overlay", "Music"],
    media: { type: "video", src: "/assets/web3-metal/dadabots-atari-vs-aphex.mp4", poster: "/assets/web3-metal/dadabots-short-02-clean.png", alt: "DADABOTS Atari Teenage Riot versus Aphex Twin vertical short-form video" },
  },
] as const;

export const homepageContent = [
  { ...featuredContent[0], lane: "Shows & Video", laneSlug: "podcast-show-overlay-design" },
  { ...featuredContent[1], lane: "Social Content", laneSlug: "short-form" },
  { ...featuredContent[3], lane: "Visual Design", laneSlug: "graphic-design" },
  { slug: "ai-builder-community", project: "AI Builder & Community", format: "AI-assisted building · community systems", title: "AI Builder & Community", summary: "AI-assisted products, creative tools, and audience systems in progress.", contribution: "Prototyping, creative technology, community programming, and product storytelling.", shortCredit: "Proof of work · prototypes · community", impact: "A growing body of practical experiments connecting what gets built with the people it is built for.", href: "/ai-builder-community", orientation: "landscape", categories: ["AI", "Community", "Build"], media: { type: "image", src: "/assets/builder-wins.webp", alt: "Placeholder image for AI Builder and Community work", width: 1280, height: 720 }, lane: "AI Builder & Community", laneSlug: "ai-builder-community" },
] as const;

export const contentLanes = [
  {
    slug: "podcast-show-overlay-design",
    title: "Shows & Video",
    intro: "Shows, interviews, and recurring video formats built from concept through production, packaging, and distribution.",
    items: ["fight-legends-development-show", "edge-show-hot-topics", "dadabots-interview", "edge-interview-social-cut", "dadabots-short-01"],
  },
  {
    slug: "short-form",
    title: "Social Content",
    intro: "Long-form conversations and product stories shaped into clear, platform-native cuts people can actually finish and share.",
    items: ["edge-interview-social-cut", "dadabots-short-01", "dadabots-short-02"],
  },
  {
    slug: "graphic-design",
    title: "Visual Design",
    intro: "YouTube thumbnails and visual systems that make long-form video recognizable, legible, and worth clicking.",
    items: ["edge-episode-packaging", "edge-nft-toonstar", "edge-nft-veecon", "edge-nft-art-basel-benzi", "edge-nft-art-basel-adam"],
  },
  {
    slug: "writing",
    title: "Editorial & Writing",
    intro: "Editorial framing, campaign copy, and publishing systems that turn a point of view into something useful, legible, and repeatable.",
    items: ["web3-metal-editorial-package"],
  },
] as const;

export const contentDisciplines = [
  { title: "Video & social", copy: "Development shows, interview cuts, launch assets, recaps, and platform-native edits in vertical and landscape formats." },
  { title: "Podcasts & interviews", copy: "Guest research, editorial framing, host scripts, recording workflows, episode packaging, and distribution." },
  { title: "Editorial & campaigns", copy: "Articles, newsletters, social systems, launch messaging, and technical ideas translated into useful stories." },
  { title: "Gaming & live programming", copy: "Developer updates, livestreams, game nights, countdown shows, AMAs, and recurring formats that reward return visits." },
  { title: "Visual packaging", copy: "Thumbnails, show identity, content architecture, captioning direction, and the connective tissue around a release." },
  { title: "Music & creator work", copy: "Artist interviews, community releases, radio programming, AI-music experiments, and creator-led editorial." },
] as const;
