export const featuredContent = [
  {
    slug: "fight-legends-development-show",
    project: "Fight Legends",
    format: "Dev update episode",
    title: "Fight Legends Dev Update",
    summary: "A recurring development format made an unfinished fighting game visible, understandable, and worth returning to between milestones.",
    contribution: "Concept, format, visual direction, editing, hosting support, episode packaging, and social distribution.",
    shortCredit: "Format · edit · episode packaging",
    impact: "25% increase in YouTube subscribers and approximately 30% higher social engagement.",
    href: "/case-studies/fight-legends",
    orientation: "landscape",
    categories: ["Video", "Gaming", "Social"],
    media: { type: "video", src: "/assets/fight-legends/dev-update-22.mp4", poster: "/assets/fight-legends/dev-update-22-poster.png", alt: "Fight Legends development update episode 22 clip" },
  },
  {
    slug: "edge-interview-social-cut",
    project: "Edge of Company",
    format: "Vertical social interview",
    title: "Edge of NFT Social Interview",
    summary: "Short-form packaging gave an interview a second life beyond the episode and created a clear on-ramp for new viewers.",
    contribution: "Guest framing, interview production, vertical edit, captioning direction, and channel packaging.",
    shortCredit: "Interview production · vertical edit · captions",
    impact: "Part of a system that added 17,800 YouTube views and grew followers 35%.",
    href: "/case-studies/edge-of-company",
    orientation: "portrait",
    categories: ["Podcast", "Interview", "Social"],
    media: { type: "video", src: "/assets/interview-short-form-web.mp4", alt: "Vertical interview clip produced for Edge of Company" },
  },
  {
    slug: "dadabots-interview",
    project: "Web3 Metal",
    format: "Interview & visual package",
    title: "DADABOTS Interview",
    summary: "An experimental subject shaped into a concise creator story without sanding off what made it strange and interesting.",
    contribution: "Interview direction, editorial framing, custom overlay design, edit, and distribution packaging.",
    shortCredit: "Interview direction · overlay design · edit",
    impact: "Connected emerging music technology to a creator audience through an accessible, personality-led format.",
    href: "/content/podcast-show-overlay-design",
    orientation: "landscape",
    categories: ["Interview", "Music", "Creator work"],
    media: { type: "video", src: "/assets/dadabots-interview-clip-web.mp4", alt: "DADABOTS interview clip produced for Web3 Metal" },
  },
  {
    slug: "edge-episode-packaging",
    project: "Edge of Company",
    format: "Visual design & packaging",
    title: "Episode packaging for the feed",
    summary: "A visual system built to make a long-form episode legible at a glance across YouTube, social, and the wider show identity.",
    contribution: "Overlay direction, title treatment, episode packaging, and social-ready visual assets.",
    shortCredit: "Overlay design · title treatment · packaging",
    impact: "A repeatable visual language for interview episodes and their social cutdowns.",
    href: "/case-studies/edge-of-company",
    orientation: "landscape",
    categories: ["Design", "Packaging", "Interview"],
    media: { type: "image", src: "/assets/future-of-storytelling.jpeg", alt: "Edge of NFT Future of Storytelling episode packaging", width: 1280, height: 720 },
  },
  {
    slug: "web3-metal-editorial-package",
    project: "Web3 Metal",
    format: "Editorial & campaign work",
    title: "Editorial systems for creator work",
    summary: "Newsletter and campaign assets that gave an experimental music project a consistent voice, cadence, and visual world.",
    contribution: "Editorial framing, campaign copy, visual direction, publishing rhythm, and audience packaging.",
    shortCredit: "Editorial direction · campaign copy · visual system",
    impact: "A repeatable publishing system for creator-led stories, releases, and community programming.",
    href: "/content/writing",
    orientation: "landscape",
    categories: ["Editorial", "Campaigns", "Creator work"],
    media: { type: "image", src: "/assets/newsletter-metal-gods.webp", alt: "Web3 Metal newsletter editorial artwork", width: 1280, height: 720 },
  },
  {
    slug: "dadabots-short-01",
    project: "Web3 Metal",
    format: "Short-form visual",
    title: "DADABOTS short-form cut 01",
    summary: "A vertical social asset that turns an artist interview into a focused, mobile-first visual moment.",
    contribution: "Interview packaging, visual direction, vertical framing, and YouTube Shorts publishing.",
    shortCredit: "Vertical edit · overlay design · publishing",
    impact: "Built to give a niche creator story a clear entry point in the social feed.",
    href: "https://youtube.com/shorts/qFyeqpp7-Gg?si=Jl42Rn_YnaDXemE3",
    external: true,
    orientation: "portrait",
    categories: ["Short Form", "Overlay", "Music"],
    media: { type: "image", src: "/assets/web3-metal/dadabots-short-01-clean.png", alt: "DADABOTS vertical short-form visual 01", width: 942, height: 1670 },
  },
  {
    slug: "dadabots-short-02",
    project: "Web3 Metal",
    format: "Short-form visual",
    title: "DADABOTS short-form cut 02",
    summary: "A second vertical treatment showing how the same interview system can produce distinct social-ready moments.",
    contribution: "Overlay design, vertical composition, short-form edit direction, and YouTube Shorts publishing.",
    shortCredit: "Vertical edit · overlay design · publishing",
    impact: "A companion cut that extends the interview’s life beyond the original conversation.",
    href: "https://youtube.com/shorts/G8jH6NHOz2I?si=xm96YirCRtFbkhYy",
    external: true,
    orientation: "portrait",
    categories: ["Short Form", "Overlay", "Music"],
    media: { type: "image", src: "/assets/web3-metal/dadabots-short-02-clean.png", alt: "DADABOTS vertical short-form visual 02", width: 937, height: 1679 },
  },
] as const;

export const homepageContent = [
  { ...featuredContent[0], lane: "Podcast / show overlay design", laneSlug: "podcast-show-overlay-design" },
  { ...featuredContent[1], lane: "Short Form", laneSlug: "short-form" },
  { ...featuredContent[3], lane: "Graphic Design", laneSlug: "graphic-design" },
  { ...featuredContent[4], lane: "Writing", laneSlug: "writing" },
] as const;

export const contentLanes = [
  {
    slug: "podcast-show-overlay-design",
    title: "Podcast / show overlay design",
    intro: "Visual systems for live shows, interviews, and recurring video formats—designed to make the conversation feel like a show.",
    items: ["fight-legends-development-show", "edge-interview-social-cut", "dadabots-interview"],
  },
  {
    slug: "short-form",
    title: "Short Form",
    intro: "Long-form conversations and product stories shaped into clear, platform-native cuts people can actually finish and share.",
    items: ["edge-interview-social-cut", "dadabots-short-01", "dadabots-short-02"],
  },
  {
    slug: "graphic-design",
    title: "Graphic Design",
    intro: "Episode packaging, title treatments, overlays, and visual assets that give content a recognizable surface and a reason to stop scrolling.",
    items: ["edge-episode-packaging"],
  },
  {
    slug: "writing",
    title: "Writing",
    intro: "Editorial framing, campaign copy, and publishing systems that turn a point of view into something useful, legible, and repeatable.",
    items: ["web3-metal-editorial-package"],
  },
] as const;

export const contentDisciplines = [
  { title: "Video & social", copy: "Development shows, interview cuts, launch assets, recaps, and platform-native edits in vertical and landscape formats." },
  { title: "Podcasts & interviews", copy: "Guest research, editorial framing, host scripts, recording workflows, episode packaging, and distribution." },
  { title: "Editorial & campaigns", copy: "Articles, newsletters, social systems, launch messaging, and technical ideas translated into useful stories." },
  { title: "Gaming & live programming", copy: "Developer updates, livestreams, game nights, countdown shows, AMAs, and recurring formats that reward return visits." },
  { title: "Visual packaging", copy: "Thumbnails, show identity, content architecture, captioning direction, and the connective tissue around a release." },
  { title: "Music & creator work", copy: "Artist interviews, community releases, radio programming, AI-music experiments, and creator-led editorial." },
] as const;
