export const navItems = [
  ["Home", "/"],
  ["Case Studies", "/case-studies"],
  ["Lab", "/lab"],
  ["Writing", "/writing"],
  ["About", "/about"],
  ["Resume", "/resume"],
  ["Contact", "/contact"],
] as const;

export const caseStudies = [
  {
    slug: "ava-labs",
    number: "01",
    title: "Ava Labs",
    role: "Developer Engagement Manager",
    summary: "Built a measurable builder-engagement system that connected discovery, conversation, program routing, and reporting.",
    challenge: "Developer outreach was happening across channels, but the path from initial contact to program participation needed stronger visibility and follow-through.",
    system: ["Search workflows for qualified builder discovery", "UTM-tagged links for channels outside native reporting", "Program routing across Elevate, Builders Hub, hackathons, and Team1", "Leadership reporting tied to engagement and intent"],
    results: ["9,000+ developers engaged", "6,900+ visits to ecosystem resources", "4,400+ initial interactions", "3,500+ continued conversations"],
    tags: ["Developer engagement", "Growth operations", "Analytics"],
    image: "/assets/builder-wins.png",
  },
  {
    slug: "cyber-metal-radio",
    number: "02",
    title: "Cyber Metal Radio",
    role: "Co-founder & Growth Lead",
    summary: "Turned a community broadcast into a recurring creator ecosystem with submissions, rankings, live programming, and participation loops.",
    challenge: "Independent AI-music creators needed more than a playlist: they needed recurring reasons to submit, listen, return, and recognize one another.",
    system: ["Weekly New Music Monday programming", "Top 15 countdown and annual specials", "Creator submission and ranking workflows", "Live broadcast, social promotion, and community operations"],
    results: ["1,765 artist submissions in 2025", "200,000+ listens", "16,000+ community interactions", "Weekly live programming"],
    tags: ["Creator ecosystem", "Programming", "Broadcast"],
  },
  {
    slug: "fight-legends",
    number: "03",
    title: "Fight Legends",
    role: "Community Manager & Marketing Lead",
    summary: "Made an in-development fighting game visible and participatory through recurring developer media and community programming.",
    challenge: "An early-stage game needed to sustain interest between product milestones and give prospective players a meaningful role in development.",
    system: ["Weekly developer update show", "Discord game nights and livestreams", "Medium articles and product storytelling", "Social campaigns supporting early-access initiatives"],
    results: ["40% increase in Discord participation", "25% increase in YouTube subscribers", "30% increase in engagement", "14+ long-form articles and papers"],
    tags: ["Gaming community", "Content systems", "Video"],
  },
  {
    slug: "edge-of-company",
    number: "04",
    title: "Edge of Company",
    role: "Podcast & Community Producer",
    summary: "Connected podcast production, social programming, live conversations, and event coverage into one audience-growth engine.",
    challenge: "A growing media company needed consistent production across podcasts, social channels, YouTube, community programming, and live events.",
    system: ["Guest preparation and live host scripts", "Recording and publishing handoffs", "YouTube production and channel management", "X Spaces and Outer Edge LA event support"],
    results: ["24,000+ additional profile visits", "35% follower growth", "28% impression growth", "49% increase in YouTube watch hours"],
    tags: ["Podcast production", "Audience growth", "Events"],
    image: "/assets/future-of-storytelling.jpeg",
  },
  {
    slug: "web3-metal",
    number: "05",
    title: "Web3 Metal",
    role: "Founder",
    summary: "Built a niche idea into a cross-platform home for creators, listeners, experiments, collaborations, and community-led media.",
    challenge: "AI-music and onchain music experiments were scattered across platforms without a durable home for collaboration and shared identity.",
    system: ["Newsletter and editorial hub", "Discord community and skills-based challenges", "Collaborative releases and creator partnerships", "Incubation of community-led projects including Cyber Metal Radio"],
    results: ["192-member focused community", "16,000 personal artist plays", "500+ artist likes", "Summer of Suno winner"],
    tags: ["Founder", "Community design", "Creative technology"],
    image: "/assets/newsletter-metal-gods.png",
  },
  {
    slug: "cointelegraph",
    number: "06",
    title: "Cointelegraph",
    role: "Social Media & Content Manager",
    summary: "Translated complex products into practical multi-client content systems designed for attention, clarity, and measurable growth.",
    challenge: "Emerging-technology clients needed distinct, credible content programs while moving quickly across launches and market conversations.",
    system: ["Multi-client editorial calendars", "Campaign copy for product launches", "Analytics-led iteration", "Coordination across editorial and design"],
    results: ["30% increase in followers and engagement", "Daily multi-client publishing", "Campaign reporting tied to growth", "Product storytelling across crypto and DeFi"],
    tags: ["Social strategy", "Editorial operations", "Client work"],
  },
] as const;
